### ISSUE TITLE
Portico in private maven repository 

### ISSUE THREAD

**Issue by onkelv** [openlvc/portico#148] opened 2015-07-25 07:03 UTC
The hardcoded look for the "portico.jar" file name via endsWith im the container class makes it nearly impossible to use portico in private maven repositorys. Maven repositorys add a version number to the jar file. So portico.jar becomes portico-2_0_1.jar. Simple solution  just use contains "portico" and contains "jar" im the Container class.

**Comment by timpokorny** [comment] 2015-07-25 08:00
G'day @onkelv,

Have pushed through a fix for this. Did a little more, as using `contains()` in both cases could yield some false positives. Because it works on the full path name, if "portico" happens to be in the path anywhere else (quite conceivable) then it may find the wrong jar. Have tested this mechanism locally a little bit and touch wood it should work fine.

I'll wait for your confirmation before closing the ticket out. Currently it is going up onto the `maintenance-2.0.1

**Closed** 2015-07-25 13:34 UTC
Labels: improvement

**Comment by timpokorny** [comment] 2015-07-25 13:41
Completed merge across into `master`.

**Comment by icemagno** [comment] 2015-07-27 16:49
Hey Tim. Why must Portico finds its own JAR? I'm using this in my forked version ( Tomcat embeded - http://icemagno.github.io/scorpio/ ) and its working fine:

String myself = new File( this.getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath() ).getAbsolutePath();

**Comment by timpokorny** [comment] 2015-07-28 00:05
G'day @icemagno - the main reason is an architectural choice from long ago.

Basically, you can extend or change the RTI's implementation by dropping properly formatted jar files into the `plugins` directory. Jar files are scanned, and any classes with a certain annotation are then loaded out and linked into the main Portico infrastructure where they can start intercepting messages. 

The core Portico handlers use the same mechanism to bootstrap the RTI. However, because the jar isn't in the `plugins` folder, and because these particular handlers are important we have to guarantee that they are loaded first. So, to do this we need to point the loading mechanism at the jar file.

I have intended for some time to replace this, as realistically nobody actually uses the extension mechanism and the bootstrap could be better solved with a single big method that just binds handlers to message types. This would be hard coded (and thus clear) and much more expressive, but it wasn't the choice at the time due to a desire to support the extension mechanism. Probably a few pieces of the infrastructure I'd change with a bit more time!

Cheers,
Tim

**Comment by icemagno** [comment] 2016-02-19 12:29
This was fixed in a briliant way.
I can confirm Portico now can be used without care about the JAR name.
Can be used embeded your own runnable JAR and in a web application (WAR).
And no more RTI_HOME var.
I think portico is now free to be in a Maven repository.

**Comment by timpokorny** [comment] 2016-02-19 14:38
No more this!:

![](http://cdn.meme.am/instances/60893446.jpg)
